import { Octokit } from "@octokit/rest";
import * as core from "@actions/core";

/**
 * ELITE AGENCY | PR REVIEWER AGENT
 * This agent analyzes GitHub Pull Request diffs and generates structured feedback.
 */

interface ReviewFeedback {
    summary: string;
    risks: string[];
    suggestions: string[];
    confidence: number;
}

export class ReviewerAgent {
    private octokit: Octokit;

  constructor(token: string) {
        this.octokit = new Octokit({ auth: token });
  }

  /**
     * Fetches the diff of a Pull Request
     */
  async getPRDiff(owner: string, repo: string, pullNumber: number): Promise<string> {
        const { data } = await this.octokit.pulls.get({
                owner,
                repo,
                pull_number: pullNumber,
                mediaType: { format: "diff" },
        });
        return data as unknown as string;
  }

  /**
     * Analyzes the diff and generates structured feedback
     */
  async analyzeDiff(diff: string): Promise<ReviewFeedback> {
        const risks: string[] = [];
        if (diff.includes("TODO") || diff.includes("FIXME")) risks.push("Found unresolved markers (TODO/FIXME).");
        if (diff.includes("console.log")) risks.push("Debugging statements found in production code.");
        if (diff.includes("process.env") && !diff.includes("zod")) risks.push("Environment variables accessed without validation.");

      return {
              summary: "Automated analysis of the proposed code changes.",
              risks,
              suggestions: ["Ensure all environment variables are validated.", "Remove debugging statements before merging."],
              confidence: 0.95,
      };
  }

  /**
     * Formats the feedback into high-end Markdown
     */
  formatFeedback(feedback: ReviewFeedback): string {
        return `
        # PR Reviewer Agent Report

        ## Summary
        ${feedback.summary}

        ## Potential Risks
        ${feedback.risks.map((r) => `- ${r}`).join("\n") || "No immediate risks identified."}

        ## Suggestions
        ${feedback.suggestions.map((s) => `- ${s}`).join("\n")}

        ---
        **Confidence Score**: \`${(feedback.confidence * 100).toFixed(0)}%\`
        *Generated by Elite Agency Reviewer Agent*
            `.trim();
  }

  /**
     * Posts the review as a comment on the PR
     */
  async postReview(owner: string, repo: string, pullNumber: number, body: string): Promise<void> {
        await this.octokit.issues.createComment({
                owner,
                repo,
                issue_number: pullNumber,
                body,
        });
  }
}

// Entry point for GitHub Action
if (require.main === module) {
    const run = async () => {
          const token = core.getInput("github-token") || process.env.GITHUB_TOKEN;
          if (!token) throw new Error("GitHub token is required.");

          const [owner, repo] = (process.env.GITHUB_REPOSITORY || "").split("/");
          const pullNumber = parseInt(process.env.GITHUB_EVENT_PULL_NUMBER || "0");

          const agent = new ReviewerAgent(token);
          const diff = await agent.getPRDiff(owner, repo, pullNumber);
          const feedback = await agent.analyzeDiff(diff);
          const markdown = agent.formatFeedback(feedback);

          await agent.postReview(owner, repo, pullNumber, markdown);
    };

  run().catch((err) => core.setFailed(err.message));
}
